# Generated by Django 3.2.9 on 2022-01-29 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 12, 57, 42, 285524), verbose_name='Date'),
        ),
    ]
