# Generated by Django 3.2.9 on 2022-01-29 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 29), verbose_name='Date'),
        ),
    ]
